[project]
name = "aegis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "clickhouse-connect>=1.10.0",
    "fastapi>=0.143.0",
    "httpx>=0.28.1",
    "openai>=3.27.0",
    "pydantic>=2.14.0",
    "pygithub>=2.10.0",
    "python-dotenv>=1.2.4",
    "uvicorn>=0.54.0",
]
