#!/usr/bin/env bash
# Regenerates the fleet-map section of fleet/context.md from fleet.json and prints how to
# push the context + workspace variables to Guild.
#
# Usage:  fleet/context.sh                       # rewrite the FLEET-MAP block in context.md
#         DRY=1 OWNER=x WORKSPACE=w SCANNER_URL=https://... fleet/context.sh   # also print the guild commands
#         APPLY=1 ...                            # run `guild workspace variable set` for real
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FLEET="$ROOT/fleet.json"
CTX="$ROOT/fleet/context.md"
OWNER="${OWNER:-<owner>}"
WORKSPACE="${WORKSPACE:-<workspace>}"
SCANNER_URL="${SCANNER_URL:-https://REPLACE-WITH-TUNNEL.trycloudflare.com}"
WARDEN_NAME="${WARDEN_NAME:-aegis-warden}"
DRY="${DRY:-0}"
APPLY="${APPLY:-0}"

python3 - "$FLEET" "$CTX" "$WARDEN_NAME" <<'PY'
import json,sys,re
fleet,ctx,warden=sys.argv[1:4]
d=json.load(open(fleet))
agents=d["agents"]; report=d.get("report_repo","?"); cron=d.get("warden",{}).get("cron","*/30 * * * *")
all_repos=[r for rs in agents.values() for r in rs]
lines=["| Agent | Repos it owns (and may write to) |","|---|---|"]
for a,rs in agents.items():
    lines.append(f"| `{a}` | "+", ".join(f"`{r}`" for r in rs)+" |")
lines.append(f"| `{warden}` | read-only over all {len(all_repos)} repos, cron `{cron}`, writes drift reports to `{report}` |")
block="\n".join(lines)+f"\n\nFLEET_REPOS value: `{','.join(all_repos)}`\nREPORT_REPO value: `{report}`\n"
start="<!-- FLEET-MAP:START (generated by fleet/context.sh, do not edit by hand) -->"
end="<!-- FLEET-MAP:END -->"
txt=open(ctx).read()
if start in txt and end in txt:
    pre,rest=txt.split(start,1); _,post=rest.split(end,1)
    txt=pre+start+"\n"+block+end+post
    open(ctx,"w").write(txt); print(f"updated fleet map in {ctx}")
else:
    print(f"markers not found in {ctx}; add {start!r} ... {end!r}", file=sys.stderr); sys.exit(1)
PY

ALL_REPOS="$(python3 -c 'import json,sys; print(",".join(r for rs in json.load(open(sys.argv[1]))["agents"].values() for r in rs))' "$FLEET")"
REPORT_REPO="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("report_repo",""))' "$FLEET")"

run() { printf '+'; printf ' %q' "$@"; printf '\n'; if [[ "$APPLY" == "1" && "$DRY" != "1" ]]; then "$@"; fi; }

echo
echo "# workspace variables (guild workspace variable set, verified in CLI v0.27.1; also editable in app.guild.ai -> Setup -> Variables)"
run guild workspace variable set --workspace "$WORKSPACE" "FLEET_REPOS=$ALL_REPOS"
run guild workspace variable set --workspace "$WORKSPACE" "SCANNER_URL=$SCANNER_URL"
run guild workspace variable set --workspace "$WORKSPACE" "REPORT_REPO=$REPORT_REPO"
run guild workspace variable set --workspace "$WORKSPACE" "AEGIS_STATUS_CONTEXT=AEGIS / security-check"
echo
echo "# workspace context: the CLI editor is interactive (no --body flag). Paste fleet/context.md, then publish."
echo "+ guild workspace context edit $OWNER~$WORKSPACE        # opens editor; paste the contents of fleet/context.md"
echo "+ guild workspace context list $OWNER~$WORKSPACE        # note the draft context-id"
echo "+ guild workspace context publish $OWNER~$WORKSPACE <context-id>"
[[ "$APPLY" == "1" && "$DRY" != "1" ]] && echo "(variables applied; context must still be pasted by hand)" || echo "(printed only; APPLY=1 sets the variables)"
