#!/usr/bin/env bash
# Regenerates the fleet-map block of fleet/context.md from fleet.json; with APPLY=1 pushes the
# workspace variables and the context (draft + publish) to Guild without an interactive editor.
#   fleet/context.sh                                             # rewrite the FLEET-MAP block, print the commands
#   APPLY=1 OWNER=andriidrok1 SCANNER_URL=https://... fleet/context.sh   # set variables + publish context
#   APPLY=1 OWNER=andriidrok1 CONTEXT_ONLY=1 fleet/context.sh          # publish the context, leave variables alone
# Vars: OWNER, WORKSPACE (default aegis), SCANNER_URL (variable skipped when unset), WARDEN_NAME, APPLY, DRY.
# `guild workspace context edit` has no --file flag (0.27.1): it spawns $EDITOR <tmpfile> through a shell,
# so EDITOR="cp <our file>" writes the file in place of a human. Verified 2026-10-09.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FLEET="$ROOT/fleet.json"; CTX="$ROOT/fleet/context.md"
OWNER="${OWNER:-<owner>}"; WORKSPACE="${WORKSPACE:-aegis}"; [[ "$WORKSPACE" == *~* ]] || WORKSPACE="$OWNER~$WORKSPACE"
SCANNER_URL="${SCANNER_URL:-}"; WARDEN_NAME="${WARDEN_NAME:-aegis-warden}"
DRY="${DRY:-0}"; APPLY="${APPLY:-0}"; CONTEXT_ONLY="${CONTEXT_ONLY:-0}"
LIVE=0; [[ "$APPLY" == "1" && "$DRY" != "1" ]] && LIVE=1

python3 - "$FLEET" "$CTX" "$WARDEN_NAME" <<'PY'
import json,sys
fleet,ctx,warden=sys.argv[1:4]
d=json.load(open(fleet)); agents=d["agents"]; report=d.get("report_repo","?"); cron=d.get("warden",{}).get("cron","*/30 * * * *")
all_repos=[r for rs in agents.values() for r in rs]
lines=["| Agent | Repos it owns (and may write to) |","|---|---|"]
for a,rs in agents.items(): lines.append(f"| `{a}` | "+", ".join(f"`{r}`" for r in rs)+" |")
lines.append(f"| `{warden}` | read-only over all {len(all_repos)} repos, cron `{cron}`, writes drift reports to `{report}` |")
block="\n".join(lines)+f"\n\nFLEET_REPOS value: `{','.join(all_repos)}`\nREPORT_REPO value: `{report}`\n"
start="<!-- FLEET-MAP:START (generated by fleet/context.sh, do not edit by hand) -->"; end="<!-- FLEET-MAP:END -->"
txt=open(ctx).read()
if start not in txt or end not in txt: sys.exit(f"markers not found in {ctx}")
pre,rest=txt.split(start,1); _,post=rest.split(end,1)
open(ctx,"w").write(pre+start+"\n"+block+end+post); print(f"updated fleet map in {ctx}")
PY

ALL_REPOS="$(python3 -c 'import json,sys; print(",".join(r for rs in json.load(open(sys.argv[1]))["agents"].values() for r in rs))' "$FLEET")"
REPORT_REPO="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("report_repo",""))' "$FLEET")"
run() { printf '+'; printf ' %q' "$@"; printf '\n'; [[ "$LIVE" == "1" ]] && "$@" || true; }

if [[ "$CONTEXT_ONLY" != "1" ]]; then
  echo "# workspace variables (also editable in app.guild.ai -> workspace -> Variables)"
  run guild workspace variable set --workspace "$WORKSPACE" "FLEET_REPOS=$ALL_REPOS"
  run guild workspace variable set --workspace "$WORKSPACE" "REPORT_REPO=$REPORT_REPO"
  run guild workspace variable set --workspace "$WORKSPACE" "AEGIS_STATUS_CONTEXT=AEGIS / security-check"
  [[ -n "$SCANNER_URL" ]] && run guild workspace variable set --workspace "$WORKSPACE" "SCANNER_URL=$SCANNER_URL" || echo "# SCANNER_URL unset, variable not touched"
fi

echo "# workspace context: draft from fleet/context.md, then publish"
echo "+ EDITOR='cp $CTX' guild --mode json workspace context edit $WORKSPACE"
if [[ "$LIVE" == "1" ]]; then
  CTX_ID="$(EDITOR="cp $CTX" guild --mode json workspace context edit "$WORKSPACE" 2>&1 | python3 -c '
import json,sys
for line in sys.stdin:
    try: d=json.loads(line)
    except Exception: continue
    if d.get("success") and "Draft context created" in d.get("message",""): print(d["message"].split()[-1])')"
  [[ -n "$CTX_ID" ]] || { echo "context draft failed (run without --mode json to see why)" >&2; exit 1; }
  run guild workspace context publish "$WORKSPACE" "$CTX_ID"
else
  echo "+ guild workspace context publish $WORKSPACE <context-id printed above>"
  echo "(printed only; APPLY=1 OWNER=<owner> fleet/context.sh applies)"
fi
