#!/usr/bin/env bash
# AEGIS credential policies: least privilege per agent on the guildai~github credential.
#   ALLOW  each sentinel the GitHub operations it needs, only on its own repos
#   DENY   each sentinel everything on every OTHER fleet repo (+ report repo): a wrong-repo write is
#          refused by Guild's credential proxy (the demo moment)
#   ALLOW  the warden read + issue ops on all fleet repos
#
#   fleet/policies.sh                                  # write fleet/policies.json, print copy-pasteable commands
#   APPLY=1 OWNER=andriidrok1 fleet/policies.sh        # apply them (CRED_ID auto-detected from `guild credentials list`)
# Vars: OWNER, CRED_ID, WORKSPACE (default aegis), WARDEN_NAME (aegis-warden), APPLY (default 0), DRY.
#
# Verified (guild 0.27.1): `guild credentials policy create <cred-id> --decision ALLOW|DENY --operations a,b
#   --workspaces w --agents owner~name --resources '<json>'`. The resource keys come from
#   `guild --mode json integration get guildai~github` -> protocol_config.policy_resources:
#   "repos" (owner/repo, fnmatch patterns ok) and "methods" (HTTP verbs). Operation names are NOT documented
#   by --help; the OpenAPI operationId form (issues_create) works for most ops. Exception found live 2026-10-09:
#   repos_list_pull_requests_associated_with_commit does NOT match by name, so every agent also has an ALLOW
#   with no operations + "methods":["GET"] on its repos (reads by HTTP verb). Policy with no ALLOW match = deny.
#
# APPLIED 2026-10-09 ~22:10 UTC on credential 01a1225e-d129-c369-0000-57053b62535b (workspace andriidrok1~aegis).
# The catch-all ALLOW-all 01a1225e-d131-02e7-0000-c3da7083897e was DELETED; what stands now:
#   sentinel-0N   ALLOW 15 named ops + GET on its 3 repos; DENY all on the other fleet repos + Akmalchan/Aegis
#   triage        ALLOW repos_get,repos_get_content,repos_get_branch + GET           on the 9 fleet repos
#   remediator    ALLOW git_*/issues_create*/add_labels/pulls_create,list,merge + GET,PUT,PATCH on the 9 fleet repos
#   verifier      ALLOW issues_update,issues_create_comment,issues_list_comments + GET on the 9 fleet repos
#   rulesmith     ALLOW ref/contents/PR/comment on andriidrok1/aegis + Akmalchan/Aegis; read + issue comment on fleet
#   onboarder     ALLOW ref/contents/PR/comment on andriidrok1/aegis + Akmalchan/Aegis; read on fleet
#   reporter      ALLOW issues_create,update,list on andriidrok1/aegis (its cron report_repo) + Akmalchan/Aegis; read on fleet
#   warden        ALLOW read + issues_create,update,comment on fleet + Akmalchan/Aegis
# Only the sentinel rules below are generated by this script; the others were created by hand (see LIVE-RUN.md).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FLEET="$ROOT/fleet.json"; OUT="$ROOT/fleet/policies.json"
OWNER="${OWNER:-}"; CRED_ID="${CRED_ID:-}"; WORKSPACE="${WORKSPACE:-aegis}"
WARDEN_NAME="${WARDEN_NAME:-aegis-warden}"; DRY="${DRY:-0}"; APPLY="${APPLY:-0}"
[[ "$WORKSPACE" == *~* ]] || WORKSPACE="${OWNER:-<owner>}~$WORKSPACE"

SENTINEL_OPS="repos_get,repos_get_content,repos_get_branch,repos_create_commit_comment,repos_list_pull_requests_associated_with_commit,repos_create_or_update_file_contents,git_create_ref,issues_create,issues_update,issues_create_comment,issues_list_for_repo,issues_list_comments,pulls_create,pulls_create_review,pulls_list"
WARDEN_OPS="repos_get,repos_get_content,issues_list_for_repo,issues_create,issues_create_comment"

python3 - "$FLEET" "$OUT" "$SENTINEL_OPS" "$WARDEN_OPS" "$WARDEN_NAME" "$WORKSPACE" <<'PY'
import json,sys
fleet,out,sops,wops,warden,ws=sys.argv[1:7]
d=json.load(open(fleet)); agents=d["agents"]; report=d.get("report_repo")
all_repos=[r for rs in agents.values() for r in rs]
def rule(agent,decision,ops,repos,note):
    return {"decision":decision,"agents":[agent],"workspaces":[ws],"operations":ops.split(",") if ops else [],
            "resources":{"repos":sorted(repos)},"note":note}
rules=[]
for a,repos in agents.items():
    others=sorted((set(all_repos)-set(repos))|({report} if report else set()))
    rules.append(rule(a,"ALLOW",sops,repos,f"{a} may act only on its {len(repos)} repos"))
    rules.append(rule(a,"DENY","",others,f"{a}: all operations denied on every other fleet repo"))
rules.append(rule(warden,"ALLOW",wops,sorted(set(all_repos)|({report} if report else set())),"warden reads every fleet repo, writes the drift report issue"))
doc={"generated_from":"fleet.json","credential":"guildai~github",
     "resources_key":"repos (verified: integration get guildai~github -> protocol_config.policy_resources; fnmatch ok). Empty operations = all.",
     "operations_note":"OpenAPI operationIds (issues_create). Unverified by --help; fallback form is github_issues_create.",
     "delete_default_rule":"After applying, delete the default unscoped ALLOW-all policy or the per-agent rules change nothing.",
     "rules":rules}
json.dump(doc,open(out,"w"),indent=2); open(out,"a").write("\n")
print(f"wrote {out} ({len(rules)} rules)")
PY

if [[ "$APPLY" == "1" && "$DRY" != "1" && -z "$CRED_ID" ]]; then
  CRED_ID="$(guild --mode json credentials list --owner "${OWNER:?OWNER required with APPLY=1}" --search github --limit 50 2>&1 | python3 -c '
import json,sys
for c in json.load(sys.stdin).get("items",[]):
    if c.get("integration",{}).get("full_name")=="guildai~github": print(c["id"]); break' || true)"
  [[ -n "$CRED_ID" ]] || { echo "no guildai~github credential: connect GitHub in app.guild.ai > Credentials, or pass CRED_ID=<id>" >&2; exit 1; }
fi
cred="${CRED_ID:-<GITHUB_CRED_ID>}"

echo; echo "# guildai~github policies (credential $cred). Copy-paste, or APPLY=1 OWNER=<owner> fleet/policies.sh"
python3 - "$OUT" "$cred" "$OWNER" <<'PY' | while IFS= read -r line; do
import json,sys,shlex
doc,cred,owner=json.load(open(sys.argv[1])),sys.argv[2],sys.argv[3]
for r in doc["rules"]:
    agent=f"{owner}~{r['agents'][0]}" if owner else f"<owner>~{r['agents'][0]}"
    ops=f" --operations {','.join(r['operations'])}" if r["operations"] else ""
    print(f"guild credentials policy create {cred} --decision {r['decision']} --agents {agent} --workspaces {r['workspaces'][0]}{ops} --resources {shlex.quote(json.dumps(r['resources'],separators=(',',':')))}   # {r['note']}")
print(f"guild credentials policy list {cred} --limit 100   # then delete the default unscoped ALLOW-all rule in app.guild.ai > Credentials > GitHub > Policies")
PY
  echo "$line"
  if [[ "$APPLY" == "1" && "$DRY" != "1" && "$line" != *"policy list"* ]]; then eval "${line%%   #*}"; fi
done
[[ "$APPLY" == "1" && "$DRY" != "1" ]] && echo "applied. Now delete the default rule (see last line)." || echo "(printed only; nothing applied)"
