// Compile-time fallback for the aegis-scanner integration (NOT wired into agent.ts).
//
// Why it exists: stream B publishes the real integration as the npm package
// `@guildai-services/__OWNER__~aegis-scanner`, whose tools are generated by Guild from openapi.yaml.
// Until that exists, this file documents the exact tool contracts (arguments = request bodies in
// openapi.yaml) so the rest of the fleet can be typed and reviewed against them.
//
// What the SDK offers for custom tools, per the Guild CLI's bundled docs (agent-dev.md):
//   - `tool({ description, inputSchema, execute })`  — an execute()-based custom tool. Useless for
//     us: agents run network-isolated, so execute() cannot reach the scanner.
//   - `guildServiceTool(name, { endpoint: ... })`      — the primitive Guild uses to AUTHOR an
//     integration package. The docs say explicitly it is not for agents ("hand-rolling service tools
//     in an agent" is listed under anti-patterns). Its signature is not documented, so it is not used.
// Conclusion: there is no supported way to declare the scanner tools locally inside an agent; the
// published integration package is the only path. Keep the import in agent.ts.
import { z } from "zod"

export const Finding = z.object({
  rule_id: z.string(),
  path: z.string(),
  start_line: z.number().int(),
  end_line: z.number().int(),
  lines: z.string(),
  message: z.string(),
  severity: z.enum(["ERROR", "WARNING", "INFO"]),
  cwe: z.string().optional(),
  fingerprint: z.string(),
  fix: z.string().optional(),
  seen_before: z.number().int().optional(),
  dismissed_before: z.boolean().optional(),
  repo_mttr_h: z.number().optional(),
})

export const ScanResult = z.object({
  repo: z.string(),
  sha: z.string(),
  base_sha: z.string().optional(),
  verdict: z.enum(["safe", "unsafe"]),
  findings: z.array(Finding),
  n_files: z.number().int().optional(),
  ms: z.number().int(),
})

export const ActionKind = z.enum([
  "status_set",
  "issue_opened",
  "issue_closed",
  "pr_opened",
  "pr_reviewed",
  "dismissed",
  "denied",
  "email",
])

/** Request bodies of the four operations, keyed by the generated Guild tool name. */
export const scannerToolInputs = {
  aegis_scanner_scan_diff: z.object({
    repo: z.string().describe("owner/name"),
    base_sha: z.string(),
    head_sha: z.string(),
    agent: z.string(),
  }),
  aegis_scanner_scan_full: z.object({ repo: z.string(), sha: z.string(), agent: z.string() }),
  aegis_scanner_record_action: z.object({
    agent: z.string(),
    repo: z.string(),
    kind: ActionKind,
    ref: z.string(),
    fingerprint: z.string().optional(),
    latency_ms: z.number().int().optional(),
    session_url: z.string().optional(),
  }),
  aegis_scanner_fleet_insights: z.object({ hours: z.number().int().default(24) }),
} as const

export type ScannerToolName = keyof typeof scannerToolInputs
export type ScanResultT = z.infer<typeof ScanResult>
export type FindingT = z.infer<typeof Finding>
